ci megalinter.yml

diff --git a/.github/workflows/mega-linter.yml b/.github/workflows/mega-linter.yml
--- a/.github/workflows/mega-linter.yml
+++ b/.github/workflows/mega-linter.yml
@@ -37,55 +37,49 @@ jobs:
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: ScribeMD Docker Cache
-        uses: ScribeMD/docker-cache@e481e638abdb45e2fa30845305c387a544cc617f
-        with:
-          key: ${{ runner.os }}-docker-image-${{ steps.cache-key.outputs.key }}
+      # - name: MegaLinter
+      #   id: ml
+      #   # https://megalinter.io/flavors
+      #   # uses: docker://oxsecurity/megalinter:latest
+      #   uses: oxsecurity/megalinter@v7.9.0
+      #   env:
+      #     #  https://megalinter.io/configuration
+      #     VALIDATE_ALL_CODEBASE: 'true'
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3.0.0
+      # - name: Archive production artifacts
+      #   if: success() || failure()
+      #   uses: actions/upload-artifact@v4.3.1
+      #   with:
+      #     name: MegaLinter reports
+      #     path: |
+      #       megalinter-reports
+      #       megalinter.log
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3.0.0
-        with:
-          version: latest
+  #   - name: Set up QEMU
+  #     uses: docker/setup-qemu-action@v3.0.0
 
-      - name: Set lowercase IMAGE_NAME
-        id: set_env
-        run: echo "IMAGE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
+  # - name: Set up Docker Buildx
+  #   uses: docker/setup-buildx-action@v3.0.0
+  #   with:
+  #     version: latest
 
-      - name: Calculate cache key
-        id: cache-key
-        run: echo "{key}=$(echo $IMAGE_NAME | sha256sum | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
+  # - name: Set lowercase IMAGE_NAME
+  #   id: set_env
+  #   run: echo "IMAGE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
 
-      - name: Cache Docker layers
-        id: cache-docker
-        uses: actions/cache@v4.0.0
-        with:
-          path: /tmp/.docker-cache
-          key: ${{ runner.os }}-docker-${{ steps.cache-key.outputs.key }}
-          restore-keys: |
-            ${{ runner.os }}-docker-
+  # - name: Calculate cache key
+  #   id: cache-key
+  #   run: echo "{key}=$(echo ${{ env.IMAGE_NAME }}| sha256sum | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
 
-      - name: MegaLinter
-        id: ml
-        # https://megalinter.io/flavors
-        # uses: docker://oxsecurity/megalinter:latest
-        uses: oxsecurity/megalinter@v7.9.0
-        env:
-          #  https://megalinter.io/configuration
-          VALIDATE_ALL_CODEBASE: 'true'
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Archive production artifacts
-        if: success() || failure()
-        uses: actions/upload-artifact@v4.3.1
-        with:
-          name: MegaLinter reports
-          path: |
-            megalinter-reports
-            megalinter.log
-
+  # - name: Cache Docker layers
+  #   id: cache-docker
+  #   uses: actions/cache@v4.0.0
+  #   with:
+  #     path: /tmp/.docker-cache
+  #     key: ${{ runner.os }}-docker-${{ steps.cache-key.outputs.key }}
+  #     restore-keys: |
+  #       ${{ runner.os }}-docker-
   # megalinter:
   #   name: MegaLinter
   #   runs-on: ubuntu-latest
