mod push_to_registry

diff --git a/.github/workflows/mega-linter.yml b/.github/workflows/mega-linter.yml
--- a/.github/workflows/mega-linter.yml
+++ b/.github/workflows/mega-linter.yml
@@ -12,118 +12,166 @@ env:
   APPLY_FIXES: all
   APPLY_FIXES_EVENT: all
   APPLY_FIXES_MODE: commit
+  REGISTRY: docker.io
+  IMAGE_NAME: ${{ github.repository }}
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
 jobs:
-  megalinter:
-    name: MegaLinter
+  push_to_registry:
+    name: Push Docker image to Docker GitHub
     runs-on: ubuntu-latest
-    permissions:
-      contents: write
-      issues: write
-      pull-requests: write
     steps:
-      # Checkout the github repository
-      - name: Checkout Code
+      - name: Check out the repo
         uses: actions/checkout@v4.1.1
-        with:
-          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
-
-      - name: ScribeMD Docker Cache
-        uses: ScribeMD/docker-cache@e481e638abdb45e2fa30845305c387a544cc617f
-        with:
-          key: ${{ runner.os }}-docker-image-${{ hashFiles('**/pnpm-lock.yaml') }}
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3.0.0
 
+      - name: Login to Docker Hub
+        if: github.event_name != 'pull_request'
+        uses: docker/login-action@v3.0.0
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_PASSWORD }}
+
       - name: Cache Docker layers
+        id: cache
         uses: actions/cache@v4.0.0
         with:
-          path: /tmp/.docker-images
-          key: ${{ runner.os }}-docker-image-${{ hashFiles('**/pnpm-lock.yaml') }}
+          path: /tmp/.buildx-cache
+          key: ${{ runner.os }}-buildx-${{ github.sha }}
+          restore-keys: |
+            ${{ runner.os }}-buildx-
 
-      - name: Save Docker Cache
-        uses: actions/cache/save@v4.0.0
         with:
-          path: /tmp/.docker-images
-          key: ${{ runner.os }}-docker-image-${{ hashFiles('**/pnpm-lock.yaml') }}
+          path: /tmp/.buildx-cache
+          key: ${{ runner.os }}-buildx-${{ github.sha }}
+      - name: Extract metadata (tags, labels) for Docker
+        id: meta
+        uses: docker/metadata-action@v4.0.0
+        with:
+          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
 
-      # - name: Load cached Docker image
-      #   run: |
-      #     if [ -f "/tmp/.docker-images/megalinter.tar" ]; then
-      #       echo "Loading cache of Docker image";
-      #       docker load < /tmp/.docker-images/megalinter.tar
-      #     fi
+      - name: Build and push Docker image
+        if: github.event_name != 'pull_request'
+        uses: docker/build-push-action@v5.1.0
+        with:
+          context: '{{defaultContext}}:src'
+          push: true
+          tags: ${{ steps.meta.outputs.tags }}
+          labels: ${{ steps.meta.outputs.labels }}
+          cache-from: type=local,src=/tmp/.buildx-cache
+          cache-to: type=local,dest=/tmp/.buildx-cache
 
-      # - name: Pull and Save Docker Image
-      #   run: |
-      #     if [ ! docker images oxsecurity/megalinter | grep -q oxsecurity/megalinter; ] then
-      #       echo "Pulling Docker image";
-      #       docker pull oxsecurity/megalinter:latest
-      #       mkdir -p /tmp/.docker-images
-      #       docker save oxsecurity/megalinter:latest > /tmp/.docker-images/megalinter.tar
-      #     fi
+  # megalinter:
+  #   name: MegaLinter
+  #   runs-on: ubuntu-latest
+  #   permissions:
+  #     contents: write
+  #     issues: write
+  #     pull-requests: write
+  #   steps:
+  #     # Checkout the github repository
+  #     - name: Checkout Code
+  #       uses: actions/checkout@v4.1.1
+  #       with:
+  #         token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
 
-      # - name: Log in to Dockerhub
-      #   uses: docker/login-action@v3.0.0
-      #   with:
-      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
-      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
+  #     - name: ScribeMD Docker Cache
+  #       uses: ScribeMD/docker-cache@e481e638abdb45e2fa30845305c387a544cc617f
+  #       with:
+  #         key: ${{ runner.os }}-docker-image-${{ hashFiles('**/pnpm-lock.yaml') }}
 
-      # - name: Pull and Build Docker Image
-      #   uses: docker/build-push-action@v5.1.0
-      #   with:
-      #     context: .
-      #     tags: areid987/megalinter:latest
-      #     outputs: type=docker, dest=/tmp/.docker-images/megalinter.tar
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v3.0.0
 
-      # - name: Move and Save Cache
-      #   run: |
-      #     rm -rf /tmp/.buildx-cache
-      #     mv /tmp/.docker-images/megalinter-new /tmp/.docker-images/megalinter
+  #     - name: Cache Docker layers
+  #       uses: actions/cache@v4.0.0
+  #       with:
+  #         path: /tmp/.docker-images
+  #         key: ${{ runner.os }}-docker-image-${{ hashFiles('**/pnpm-lock.yaml') }}
 
-      # - name: MegaLinter
-      #   id: ml
-      #   # https://megalinter.io/flavors
-      #   uses: docker://oxsecurity/megalinter:latest
-      #   env:
-      #     #  https://megalinter.io/configuration
-      #     VALIDATE_ALL_CODEBASE: 'true'
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      # # Upload MegaLinter artifacts
-      # - name: Archive production artifacts
-      #   if: success() || failure()
-      #   uses: actions/upload-artifact@v4.3.1
-      #   with:
-      #     name: MegaLinter reports
-      #     path: |
-      #       /tmp/.docker-images/megalinter.tar
-      #       megalinter-reports
-      #       megalinter.log
-      # #  Create pull request if applicablie
-      # - name: Create Pull Request with applied fixes
-      #   id: cpr
-      #   if: steps.ml.outputs.has_updated_sources == 1 && (env.APPLY_FIXES_EVENT == 'all' || env.APPLY_FIXES_EVENT == github.event_name) && env.APPLY_FIXES_MODE == 'pull_request' && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) && !contains(github.event.head_commit.message, 'skip fix')
-      #   uses: peter-evans/create-pull-request@b1ddad2c994a25fbc81a28b3ec0e368bb2021c50
-      #   with:
-      #     token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
-      #     commit-message: '[MegaLinter] Apply linters automatic fixes'
-      #     title: '[MegaLinter] Apply linters automatic fixes'
-      #     labels: bot
+  #     - name: Save Docker Cache
+  #       uses: actions/cache/save@v4.0.0
+  #       with:
+  #         path: /tmp/.docker-images
+  #         key: ${{ runner.os }}-docker-image-${{ hashFiles('**/pnpm-lock.yaml') }}
 
-      # - name: Create PR output
-      #   if: steps.ml.outputs.has_updated_sources == 1 && (env.APPLY_FIXES_EVENT == 'all' || env.APPLY_FIXES_EVENT == github.event_name) && env.APPLY_FIXES_MODE == 'commit' && github.ref != 'refs/heads/main' && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) && !contains(github.event.head_commit.message, 'skip fix')
-      #   run: sudo chown -Rc $UID .git/
+  # - name: Load cached Docker image
+  #   run: |
+  #     if [ -f "/tmp/.docker-images/megalinter.tar" ]; then
+  #       echo "Loading cache of Docker image";
+  #       docker load < /tmp/.docker-images/megalinter.tar
+  #     fi
 
-      # - name: Commit and push applied linter fixes
-      #   if: steps.ml.outputs.has_updated_sources == 1 && (env.APPLY_FIXES_EVENT == 'all' || env.APPLY_FIXES_EVENT == github.event_name) && env.APPLY_FIXES_MODE == 'commit' && github.ref != 'refs/heads/main' && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) && !contains(github.event.head_commit.message, 'skip fix')
-      #   uses: stefanzweifel/git-auto-commit-action@e040c596f0a65570b339c60818081175bcf82d11
-      #   with:
-      #     branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
-      #     commit_message: '[MegaLinter] Apply linters fixes'
-      #     commit_user_name: megalinter-bot
-      #     commit_user_email: read.musik@gmail.com
+  # - name: Pull and Save Docker Image
+  #   run: |
+  #     if [ ! docker images oxsecurity/megalinter | grep -q oxsecurity/megalinter; ] then
+  #       echo "Pulling Docker image";
+  #       docker pull oxsecurity/megalinter:latest
+  #       mkdir -p /tmp/.docker-images
+  #       docker save oxsecurity/megalinter:latest > /tmp/.docker-images/megalinter.tar
+  #     fi
+
+  # - name: Log in to Dockerhub
+  #   uses: docker/login-action@v3.0.0
+  #   with:
+  #     username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
+
+  # - name: Pull and Build Docker Image
+  #   uses: docker/build-push-action@v5.1.0
+  #   with:
+  #     context: .
+  #     tags: areid987/megalinter:latest
+  #     outputs: type=docker, dest=/tmp/.docker-images/megalinter.tar
+
+  # - name: Move and Save Cache
+  #   run: |
+  #     rm -rf /tmp/.buildx-cache
+  #     mv /tmp/.docker-images/megalinter-new /tmp/.docker-images/megalinter
+
+  # - name: MegaLinter
+  #   id: ml
+  #   # https://megalinter.io/flavors
+  #   uses: docker://oxsecurity/megalinter:latest
+  #   env:
+  #     #  https://megalinter.io/configuration
+  #     VALIDATE_ALL_CODEBASE: 'true'
+  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  # # Upload MegaLinter artifacts
+  # - name: Archive production artifacts
+  #   if: success() || failure()
+  #   uses: actions/upload-artifact@v4.3.1
+  #   with:
+  #     name: MegaLinter reports
+  #     path: |
+  #       /tmp/.docker-images/megalinter.tar
+  #       megalinter-reports
+  #       megalinter.log
+  # #  Create pull request if applicablie
+  # - name: Create Pull Request with applied fixes
+  #   id: cpr
+  #   if: steps.ml.outputs.has_updated_sources == 1 && (env.APPLY_FIXES_EVENT == 'all' || env.APPLY_FIXES_EVENT == github.event_name) && env.APPLY_FIXES_MODE == 'pull_request' && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) && !contains(github.event.head_commit.message, 'skip fix')
+  #   uses: peter-evans/create-pull-request@b1ddad2c994a25fbc81a28b3ec0e368bb2021c50
+  #   with:
+  #     token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
+  #     commit-message: '[MegaLinter] Apply linters automatic fixes'
+  #     title: '[MegaLinter] Apply linters automatic fixes'
+  #     labels: bot
+
+  # - name: Create PR output
+  #   if: steps.ml.outputs.has_updated_sources == 1 && (env.APPLY_FIXES_EVENT == 'all' || env.APPLY_FIXES_EVENT == github.event_name) && env.APPLY_FIXES_MODE == 'commit' && github.ref != 'refs/heads/main' && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) && !contains(github.event.head_commit.message, 'skip fix')
+  #   run: sudo chown -Rc $UID .git/
+
+  # - name: Commit and push applied linter fixes
+  #   if: steps.ml.outputs.has_updated_sources == 1 && (env.APPLY_FIXES_EVENT == 'all' || env.APPLY_FIXES_EVENT == github.event_name) && env.APPLY_FIXES_MODE == 'commit' && github.ref != 'refs/heads/main' && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) && !contains(github.event.head_commit.message, 'skip fix')
+  #   uses: stefanzweifel/git-auto-commit-action@e040c596f0a65570b339c60818081175bcf82d11
+  #   with:
+  #     branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
+  #     commit_message: '[MegaLinter] Apply linters fixes'
+  #     commit_user_name: megalinter-bot
+  #     commit_user_email: read.musik@gmail.com
