ci workflow docker cache mod fix 13

diff --git a/.github/workflows/mega-linter.yml b/.github/workflows/mega-linter.yml
--- a/.github/workflows/mega-linter.yml
+++ b/.github/workflows/mega-linter.yml
@@ -40,6 +40,7 @@ jobs:
       - name: Calculate cache key
         id: cache-key
         run: echo "::set-output name=key::$(echo $IMAGE_NAME | sha256sum | cut -d ' ' -f 1)"
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
         with:
@@ -65,15 +66,21 @@ jobs:
         run: |
           mkdir -p /tmp/docker-images
           if [ -f /tmp/docker-images/${{ env.IMAGE_NAME }}.tar ]; then
-            docker load < /tmp/docker-images/${{ env.IMAGE_NAME }}.tar
+            docker load < /tmp/docker-images/${{ env.IMAGE_NAME }}.tar || true
           fi
 
       - name: Pull Docker image
         if: steps.cache-docker.outputs.cache-hit != 'true'
+        id: pull-docker-image
+        continue-on-error: true
         run: |
-          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
-          mkdir -p /tmp/docker-images
-          docker save ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} > /tmp/.docker-images/${{ env.IMAGE_NAME }}.tar
+          if docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}; then
+            echo "${{ env.IMAGE_NAME }} pulled successfully"
+            echo "DOCKER_IMAGE_EXISTS=true" >> $GITHUB_ENV
+          else
+            echo "${{ env.IMAGE_NAME }} not found. Will use fallback."
+            echo "DOCKER_IMAGE_EXISTS=false" >> $GITHUB_ENV
+          fi
 
       - name: Build and push Docker image
         id: build-and-push
